### ISSUE TITLE
container env flags as a question answer 

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/backend-ziadamer#24]
container `env` flags as a question answer 

any dockerfile env directive is a flag 

we can use an equation for the random `UUID` flags would not be randomized any more 
hash("`userID`" + "`questionID`" + "`containerID`" )
and unhash it when checking the answer of the user and compare it to the unhashed 

and store in the active containers table 
resource_group_name  to be deleted later                             
containerID to use in hash
user ID occupying the container

**Comment by ziad-amer-1** [comment]
DONE!
